name: Update Linear Forecast

on:
  workflow_dispatch:  # Allow manual triggering only

jobs:
  update-forecast:
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      id-token: write  # Required for Google Cloud authentication
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        
    - name: Cache pip dependencies
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-forecast-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-forecast-
          ${{ runner.os }}-pip-
          
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt --quiet
        
    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
        
    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: little-fax
        
    - name: Verify Google Cloud Storage access
      run: |
        gcloud auth list
        gsutil ls gs://1-million-beers/
        
    - name: Run linear forecast update
      run: |
        python scripts/update_linear_forecast.py
        cat content_README.md content_forecast.txt > README.md

    - name: Commit and push updated plots
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add beer_counts_with_outliers.html beer_counts_with_outliers.png beer_counts_with_linear_forecast.html beer_counts_with_linear_forecast.png content_forecast.txt README.md
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "🤖 Update beer forecast plots and README (automated update)"
          git push
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
